const Home = {
    id: 0,
    banner_tagline: '',
    banner_heading: '',
    banner_content: '',
    about_main_heading: '',
    about_main_heading_content: '',
    about_sub_heading: '',
    about_sub_heading_content: '',
    work_steps_heading_1: '',
    work_steps_content_1: '',
    work_steps_heading_2: '',
    work_steps_content_2: '',
    work_steps_heading_3: '',
    work_steps_content_3: '',
    why_choose_heading: '',
    why_choose_box_heading_1: '',
    why_choose_box_content_1: '',
    why_choose_box_heading_2: '',
    why_choose_box_content_2: '',
    why_choose_box_heading_3: '',
    why_choose_box_content_3: '',
    why_choose_box_heading_4: '',
    why_choose_box_content_4: '',
    why_choose_box_heading_5: '',
    why_choose_box_content_5: '',
    why_choose_box_heading_6: '',
    why_choose_box_content_6: '',
    why_choose_box_heading_7: '',
    why_choose_box_content_7: '',
    why_choose_box_heading_8: '',
    why_choose_box_heading_8: '',
    createdby: 1,
    createdon: new Date(),
    modifiedby: 1,
    modifiedon: new Date()
}

module.exports = Home;