const Home = {
    Id: 0,
    BannerTagline: '',
    BannerHeading: '',
    BannerContent: '',
    AboutMainHeading: '',
    AboutMainHeadingContent: '',
    AboutSubHeading: '',
    AboutSubHeadingContent: '',
    WorkStepsHeading1: '',
    WorkStepsContent1: '',
    WorkStepsHeading2: '',
    WorkStepsContent2: '',
    WorkStepsHeading3: '',
    WorkStepsContent3: '',
    WhyChooseHeading: '',
    WhyChooseBoxHeading1: '',
    WhyChooseBoxContent1: '',
    WhyChooseBoxHeading2: '',
    WhyChooseBoxContent2: '',
    WhyChooseBoxHeading3: '',
    WhyChooseBoxContent3: '',
    WhyChooseBoxHeading4: '',
    WhyChooseBoxContent4: '',
    WhyChooseBoxHeading5: '',
    WhyChooseBoxContent5: '',
    WhyChooseBoxHeading6: '',
    WhyChooseBoxContent6: '',
    WhyChooseBoxHeading7: '',
    WhyChooseBoxContent7: '',
    WhyChooseBoxHeading8: '',
    WhyChooseBoxContent8: '',
    CreatedBy: 1,
    CreatedOn: new Date(),
    ModifiedBy: 1,
    ModifiedOn: new Date()
}

module.exports = Home;